import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Instagram Clone 2022</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* Header */}
      <p className='text-green-500 bg-red-600'>naber</p>
      {/* Feed */}

      {/* Modal */}
    </div>
  );
}
