import Head from 'next/head';
import Feed from '../components/Feed';
import Header from '../components/Header';
import UploadModal from '../components/UploadModal';

export default function Home() {
  return (
    <div className='min-h-screen bg-gray-50'>
      <Head>
        <title>Instagram Clone 2022</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <Feed />
      <UploadModal />
    </div>
  );
}
